### ISSUE TITLE
ENTRAINEURS : renommer la 1re colonne en "Id" (à la place de "Entraîneur" et la déplacer en dernière position

### ISSUE THREAD

**Issue by deromeem** [deromeem/FootRegion#1]
Il faut modifier la vue liste des entraîneurs.

**Comment by deromeem** [comment]
Il faut modifier la vie liste des Entraîneurs.

**Comment by RubeanAtoembe** [comment]
vue liste modifier la colonne "Id" est en dernière position la 1ère est l'email
