### ISSUE TITLE
DIRECTEURS : ERREUR AU TRI DE LA COLONNE PRENOM (VUE DE LISTE)

### ISSUE THREAD

**Issue by Saiddev75** [deromeem/FootRegion#13]
lorsque l'on clique sur l'icone pour trier la colonne prénom cela nous renvoie à une page d'erreur :
"×
Erreur
Unknown column 'd.prenom' in 'order clause'"

**Comment by SebastienML** [comment]
Corrigé :+1: :1st_place_medal:
