### ISSUE TITLE
MATCHS: 404 Affichage introuvable [name, type, prefix] : matches, html, footregionView

### ISSUE THREAD

**Issue by MLeblond21** [deromeem/FootRegion#5]
Affiche l'erreur "404 Affichage introuvable [name, type, prefix] : matches, html, footregionView" lors de la fermeture du menu modifier et nouveau (Crée quand même)

**Comment by Quentin-RIBAU** [comment]
Erreur corrigée, les liens marchent maintenant dans tous les cas.
